[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
cbor_metadata = true
ffi = true
optimizer = true
optimizer_runs = 15000
evm_version = "shanghai"
ast = true
build_info = true
extra_output = ["storageLayout"]
gas_reports = ["*"]
fs_permissions = [{ access = "read-write", path = "./" }]

[profile.zksync]
src = 'src'
libs = ['lib']
fallback_oz = true
is_system = false
mode = "3"
cbor_metadata = true
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
gas_reports = ["*"]

[rpc_endpoints]
mainnet = "${MAINNET_RPC}"
sepolia = "${SEPOLIA_RPC}"
fi_sepolia = "${FI_SEPOLIA_RPC}"
arbitrum_sepolia = "${ARBITRUM_SEPOLIA_RPC}"

[etherscan]
mainnet = { key = "${MAINNET_ETHERSCAN_KEY}" }
sepolia = { key = "${MAINNET_ETHERSCAN_KEY}" }
fi_sepolia = { url = "https://fi-sepolia-explorer.ether.fi/api", key = "5P1ZGHEFGJUN2N1T9NY6NVVDXQDJKPMD2Z" }
arbitrum_sepolia = { key = "${ARBISCAN_KEY}" }
